[tool.poetry]
name = "boids"
version = "0.1.0"
description = ""
authors = ["samwedge <samwedge@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
p5 = "^0.7.1"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
